workflows:
  oneview_android_release:
    name: OneView Budget APK
    max_build_duration: 60
    environment:
      flutter: 3.22.2
    scripts:
      - name: Versions
        script: |
          flutter --version
          dart --version
      - name: Pub get
        script: flutter pub get
      - name: Build APK (universel)
        script: |
          flutter build apk --release
          echo "== Recherche d'APKs =="
          mkdir -p cm_artifacts
          find build -type f -name "*.apk" -print -exec cp -v {} cm_artifacts/ \; || true
          echo "== Contenu cm_artifacts =="
          ls -la cm_artifacts || true
    artifacts:
      - cm_artifacts/*.apk
