workflows:
  android-apk:
    name: OneView Budget APK (universel)
    max_build_duration: 60
    environment:
      flutter: 3.22.2
    scripts:
      - name: Versions
        script: |
          flutter --version
          dart --version
      - name: Sanity check
        script: |
          [ -f pubspec.yaml ] || { echo "pubspec.yaml introuvable"; exit 1; }
          [ -f lib/main.dart ] || { echo "lib/main.dart introuvable"; exit 1; }
      - name: Dépendances
        script: flutter pub get
      - name: Build APK (universel)
        script: |
          flutter build apk --release
          echo "== APKs trouvés =="
          find build -type f -name "*.apk" -print || true
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/*.apk

  android-apk-split:
    name: OneView Budget APK (split ABI)
    max_build_duration: 60
    environment:
      flutter: 3.22.2
    scripts:
      - name: Versions
        script: |
          flutter --version
          dart --version
      - name: Sanity check
        script: |
          [ -f pubspec.yaml ] || { echo "pubspec.yaml introuvable"; exit 1; }
          [ -f lib/main.dart ] || { echo "lib/main.dart introuvable"; exit 1; }
      - name: Dépendances
        script: flutter pub get
      - name: Build APK (split ABI)
        script: |
          flutter build apk --release --split-per-abi
          echo "== APKs trouvés =="
          find build -type f -name "*.apk" -print || true
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/*.apk
