workflows:
  android-apk:
    name: OneView Budget APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Vérifier la structure du projet
        script: |
          echo "== Vérification des fichiers essentiels =="
          ls -la
          if [ ! -f "pubspec.yaml" ]; then echo "❌ Fichier pubspec.yaml introuvable"; exit 1; fi
          if [ ! -f "lib/main.dart" ]; then echo "❌ Fichier lib/main.dart introuvable"; exit 1; fi

      - name: Version Flutter
        script: flutter --version

      - name: Installer les dépendances
        script: flutter pub get

      - name: Build APK Release
        script: |
          flutter build apk --release
          echo "== Liste des APKs générés =="
          find build/app/outputs -type f -name "*.apk" || echo "Aucun APK trouvé !"

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
