workflows:
  oneview_android_release:
    name: OneView Android APK
    max_build_duration: 60

    environment:
      flutter: 3.22.2        # version fixe de Flutter
      java: 17               # JDK compatible Gradle/AGP récents

    scripts:
      - name: Versions & préparation
        script: |
          set -euxo pipefail
          flutter --version
          java -version
          chmod +x android/gradlew

      - name: Nettoyage
        script: flutter clean

      - name: Dépendances
        script: flutter pub get

      - name: Sanity checks
        script: |
          test -f lib/main.dart
          test -f android/app/src/main/AndroidManifest.xml

      - name: Build APKs (split + universel)
        script: |
          # APKs par ABI (armeabi-v7a, arm64, x86_64)
          flutter build apk --release --split-per-abi
          # APK universel (facile à installer pour tester vite)
          flutter build apk --release
          echo "== Dossier APK Flutter =="
          ls -la build/app/outputs/flutter-apk || true

      - name: Collecte des artefacts
        script: |
          set -eux
          mkdir -p cm_artifacts
          cp -v build/app/outputs/flutter-apk/*.apk cm_artifacts/
          echo "== Artefacts à publier =="
          ls -la cm_artifacts

    artifacts:
      - cm_artifacts/*.apk
