workflows:
  android-apk:
    name: OneView Budget APK
    max_build_duration: 60
    environment:
      flutter: 3.22.2
      java: 17

    scripts:
      - name: Vérifier les versions
        script: |
          flutter --version
          dart --version
          ./android/gradlew -v || true

      - name: Nettoyage et dépendances
        script: |
          flutter clean
          flutter pub get
          ./android/gradlew -p android clean

      - name: Construction APK (via Gradle)
        script: |
          set -euxo pipefail
          ./android/gradlew -p android :app:assembleRelease
          echo "== APKs trouvés =="
          find android/app/build/outputs/apk -type f -name "*.apk" -print

      - name: Collecte des artefacts
        script: |
          mkdir -p cm_artifacts
          cp -v android/app/build/outputs/apk/release/*.apk cm_artifacts/ || true
          cp -v android/app/build/outputs/apk/**/*.apk cm_artifacts/ || true
          echo "== Contenu cm_artifacts =="
          ls -la cm_artifacts || true

    artifacts:
      - cm_artifacts/*.apk
      - android/app/build/outputs/apk/**/*.apk
