workflows:
  oneview_android_release:
    name: OneView Android APK
    max_build_duration: 60
    environment:
      flutter: 3.22.2
    scripts:
      - name: Versions
        script: |
          flutter --version
          dart --version
      - name: Clean
        script: flutter clean
      - name: Pub get
        script: flutter pub get
      - name: Sanity check
        script: |
          [ -f lib/main.dart ] || { echo "lib/main.dart introuvable"; exit 1; }
      - name: Build APK (universel)
        script: |
          flutter build apk --release
          echo "== APKs trouvés =="
          find build -name "*.apk" -maxdepth 5 -print || true
    artifacts:
      - build/**/outputs/**/*.apk
