workflows:
  oneview_android_release:
    name: OneView Budget APK
    max_build_duration: 60
    environment:
      flutter: 3.22.2
    scripts:
      - name: Versions
        script: |
          flutter --version
          dart --version

      - name: Pub get
        script: flutter pub get

      - name: Build APK (universal + split)
        script: |
          set -e
          # 1) build universel
          flutter build apk --release
          # 2) build split (ABI)
          flutter build apk --release --split-per-abi || true

          echo "== ARBRE DU DOSSIER build (top 500) =="
          find build -maxdepth 6 -type f | head -n 500 || true

          echo "== COPIE DES APKs =="
          mkdir -p cm_artifacts
          # chemins classiques Flutter récents
          cp -v build/app/outputs/flutter-apk/*.apk cm_artifacts/ 2>/dev/null || true
          # anciens chemins Gradle
          cp -v android/app/build/outputs/apk/release/*.apk cm_artifacts/ 2>/dev/null || true
          # filet de sécurité (attrape TOUT .apk sous build/)
          find build -type f -name "*.apk" -print -exec cp -v {} cm_artifacts/ \; || true

          echo "== CONTENU cm_artifacts =="
          ls -la cm_artifacts || true

          # échouer si rien trouvé (pour qu’on voie clair)
          if [ -z "$(ls -A cm_artifacts 2>/dev/null)" ]; then
            echo "AUCUN APK TROUVÉ. Vérifie les logs ci-dessus (chemins)."
            exit 2
          fi

    artifacts:
      - cm_artifacts/*.apk
