workflows:
  android-apk:
    name: OneView Budget APK
    max_build_duration: 60
    environment:
      flutter: 3.22.2
      java: 17

    scripts:
      - name: Sanity check
        script: |
          set -e
          echo "== Arbo repo =="
          ls -la
          test -f pubspec.yaml
          test -f lib/main.dart

      - name: Versions
        script: |
          flutter --version
          dart --version

      - name: Clean & deps
        script: |
          flutter clean
          flutter pub get

      - name: Build APK (universel)
        script: |
          set -e
          flutter build apk --release -v
          echo "== Fichiers trouvés sous build/ =="
          find build -maxdepth 5 -type f -print || true
          echo "== APKs trouvés =="
          find build -type f -name "*.apk" -print || true

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/*.apk
