workflows:
  oneview_android_release:
    name: OneView Android APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Nettoyage complet du cache
        script: |
          flutter clean
          rm -rf ~/.pub-cache
          rm -rf build
      - name: Vérifier Flutter
        script: flutter --version
      - name: Nettoyage
        script: flutter clean
      - name: Dépendances
        script: flutter pub get
      - name: Sanity check (main.dart présent)
        script: |
          if [ ! -f lib/main.dart ]; then
            echo "ERREUR: lib/main.dart introuvable"; exit 1;
          fi
      - name: Build APK (split par ABI)
        script: flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/app-*-release.apk
    environment:
      flutter: 3.22.2
