workflows:
  oneview_android_release:
    name: OneView Android APK
    max_build_duration: 60
    environment:
      flutter: 3.22.2

    scripts:
      - name: Vérifier les versions
        script: |
          flutter --version
          dart --version

      - name: Nettoyage
        script: flutter clean

      - name: Récupération des dépendances
        script: flutter pub get

      - name: Vérification du main.dart
        script: |
          [ -f lib/main.dart ] || { echo "ERREUR : lib/main.dart introuvable"; exit 1; }

      - name: Build APK (universel)
        script: |
          flutter build apk --release
          echo "== APKs trouvés =="
          find build -type f -name "*.apk" -print || true

      - name: Lister le dossier de sortie
        script: |
          echo "== Contenu du dossier flutter-apk =="
          ls -la build/app/outputs/flutter-apk || true

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/*.apk
