workflows:
  oneview_android_release:
    name: OneView Android APK
    max_build_duration: 60
    environment:
      flutter: 3.22.2
      java: 17

    scripts:
      - name: Versions & préparation
        script: |
          set -euxo pipefail
          flutter --version
          java -version
          chmod +x android/gradlew

      - name: Nettoyage
        script: flutter clean

      - name: Dépendances
        script: flutter pub get

      - name: Build APK (universel)
        script: |
          flutter build apk --release
          echo "== APKs trouvés =="
          find build/app/outputs -type f -name "*.apk" -print

      - name: Collecte des artefacts
        script: |
          mkdir -p "$CM_EXPORT_DIR"
          # copie tous les APKs générés (quel que soit le sous-dossier)
          find build/app/outputs -type f -name "*.apk" -exec cp -v {} "$CM_EXPORT_DIR"/ \;
          echo "== Contenu $CM_EXPORT_DIR =="
          ls -la "$CM_EXPORT_DIR"

    artifacts:
      - $CM_EXPORT_DIR/*.apk
