workflows:
  oneview_android_release:
    name: OneView Android APK
    max_build_duration: 60

    environment:
      flutter: 3.22.2
      java: 17

    scripts:
      - name: Versions & préparation
        script: |
          set -euxo pipefail
          flutter --version
          java -version
          chmod +x android/gradlew

      - name: Nettoyage
        script: flutter clean

      - name: Dépendances
        script: flutter pub get

      - name: Vérification
        script: |
          test -f lib/main.dart
          test -f android/app/src/main/AndroidManifest.xml

      - name: Build APK universel
        script: |
          flutter build apk --release
          echo "== Liste des fichiers générés =="
          find build/app/outputs -type f -name "*.apk" || true

      - name: Collecte des artefacts
        script: |
          mkdir -p cm_artifacts
          cp -v build/app/outputs/**/*.apk cm_artifacts/ || echo "⚠️ Aucun APK trouvé"
          echo "== Contenu de cm_artifacts =="
          ls -la cm_artifacts || true

    artifacts:
      - cm_artifacts/*.apk
      - name: Collecte des artefacts
        script: |
          set -eux
          mkdir -p cm_artifacts
          cp -v build/app/outputs/flutter-apk/*.apk cm_artifacts/
          echo "== Artefacts à publier =="
          ls -la cm_artifacts

    artifacts:
      - cm_artifacts/*.apk
