workflows:
  android-apk:
    name: OneView Budget APK (universel)
    max_build_duration: 60
    environment:
      flutter: 3.22.2
    scripts:
      - name: Versions
        script: |
          flutter --version
          dart --version
      - name: Pub get
        script: flutter pub get
      - name: Build APK (universel)
        script: |
          flutter build apk --release
          echo "== Liste build =="
          ls -la build || true
          echo "== Recherche d'APKs =="
          # Copie tout APK trouvé dans un dossier dédié
          mkdir -p cm_artifacts
          find build -type f -name "*.apk" -print -exec cp -v {} cm_artifacts/ \; || true
          echo "== Contenu cm_artifacts =="
          ls -la cm_artifacts || true
    artifacts:
      - cm_artifacts/*.apk

  android-apk-split:
    name: OneView Budget APK (split ABI)
    max_build_duration: 60
    environment:
      flutter: 3.22.2
    scripts:
      - name: Versions
        script: |
          flutter --version
          dart --version
      - name: Pub get
        script: flutter pub get
      - name: Build APK (split)
        script: |
          flutter build apk --release --split-per-abi
          echo "== Recherche d'APKs (split) =="
          mkdir -p cm_artifacts
          find build -type f -name "*.apk" -print -exec cp -v {} cm_artifacts/ \; || true
          ls -la cm_artifacts || true
    artifacts:
      - cm_artifacts/*.apk      - name: Sanity check
        script: |
          [ -f pubspec.yaml ] || { echo "pubspec.yaml introuvable"; exit 1; }
          [ -f lib/main.dart ] || { echo "lib/main.dart introuvable"; exit 1; }
      - name: Dépendances
        script: flutter pub get
      - name: Build APK (split ABI)
        script: |
          flutter build apk --release --split-per-abi
          echo "== APKs trouvés =="
          find build -type f -name "*.apk" -print || true
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/*.apk
