workflows:
  oneview_android_release:
    name: OneView Android APK
    max_build_duration: 60

    environment:
      flutter: 3.22.2   # une seule version, claire et fixe

    scripts:
      - name: Versions
        script: |
          flutter --version
          dart --version

      - name: Nettoyage léger
        script: flutter clean

      - name: Dépendances
        script: flutter pub get

      - name: Sanity check (main.dart présent)
        script: |
          if [ ! -f lib/main.dart ]; then
            echo "ERREUR: lib/main.dart introuvable"; exit 1;
          fi

      - name: Build APK (split par ABI)
        script: |
          flutter build apk --release --split-per-abi
          echo "== Contenu du dossier d'APKs =="
          ls -la build/app/outputs/flutter-apk || true

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
