workflows:
  android-apk:
    name: OneView Budget APK (force artifact)
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Vérification du projet
        script: |
          echo "== Contenu racine =="
          ls -la
          if [ ! -f "pubspec.yaml" ]; then echo "❌ pubspec.yaml manquant"; exit 1; fi
          if [ ! -f "lib/main.dart" ]; then echo "❌ lib/main.dart manquant"; exit 1; fi

      - name: Version Flutter
        script: flutter --version

      - name: Dépendances
        script: flutter pub get

      - name: Build APK (universel)
        script: |
          echo "== Build APK =="
          flutter build apk --release || { echo "❌ Build échouée"; exit 1; }
          echo "== Recherche d'APKs =="
          mkdir -p cm_artifacts
          find . -type f -name "*.apk" -print -exec cp -v {} cm_artifacts/ \; || true
          echo "== Contenu du dossier cm_artifacts =="
          ls -la cm_artifacts || echo "⚠️ Aucun APK trouvé"

    artifacts:
      - cm_artifacts/*.apk
