> Younes:
name: oneview_budget_flutter
description: Application de gestion financière moderne et intelligente
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / Typo
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  # Animations fluides (bouton, arcs, jauges, entrées)
  flutter_animate: ^4.5.0

  # Jauges (pour le popup "Modèle parfait")
  syncfusion_flutter_gauges: ^25.2.0

  # Charts simples (barres épargne/provisions si besoin d’évolution)
  fl_chart: ^0.68.0

  # Effets blur / glass (pour la carte et le popup)
  blur: ^4.0.0

  # Petits helpers (couleurs dégradées, icônes optionnelles)
  gradient_borders: ^1.0.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
